---
- hosts: localhost
  connection: local
  gather_facts: no
  become: true
  
  vars:
    IMAGE:
      - rhel8
#     - ubuntu2004
    
    CONFIG:
      rhel8:
        cfg: ks.cfg
        size: 10
        iso: REDHAT/rhel-8.2-x86_64-dvd.iso
        os: { kvm: "rhel8.2", vmw: "" }
      ubuntu2004:
        cfg: preseed.cfg
        size: 10
        iso: UBUNTU/ubuntu-20.04-live-server-amd64.iso
        os: { kvm: "ubuntu20.04", vmw: "" }
    
    NAME: "{{ item }}"
    DOMAIN: "img_{{ item }}"
    CFG: "{{ CONFIG[item].cfg }}"
    SIZE: "{{ CONFIG[item].size }}"
    ISO: "{{ ISO_DIR }}/{{ CONFIG[item].iso }}"
    OS: "{{ CONFIG[item].os }}"

    ISO_DIR: /mnt/depot/iso
    STORAGE: VM2


  tasks:

  - name: Building KVM images.
    include_tasks: "_LIB_/kvm-factory.yml"
    with_items: "{{ IMAGE }}"

  - name: Building VMware images.
    include_tasks: "_LIB_/vmw-factory.yml"
    with_items: "{{ IMAGE }}"
