---
- hosts: localhost
  connection: local
  gather_facts: no
  become: true
  
  vars:
    PROVISION: VMW    # KVM, KVM_INITRD
    DELETE_IMAGES: false

    IMAGE:
      - rhel7
#     - ubuntu2004
    
    CONFIG:
      rhel8:
        cfg: ks.cfg
        size: 10
        iso: REDHAT/rhel-8.2-x86_64-dvd.iso
        os: { kvm: "rhel8.2", vmw: "rhel8_64Guest"  }
      rhel7:
        cfg: ks.cfg
        size: 10
        iso: REDHAT/rhel-7.8-x86_64-dvd.iso
        os: { kvm: "rhel7.8", vmw: "rhel7_64Guest"  }
      ubuntu2004:
        cfg: preseed.cfg
        size: 10
        iso: UBUNTU/ubuntu-20.04-live-server-amd64.iso
        os: { kvm: "ubuntu20.04", vmw: "ubuntu64Guest" }

    NAME: "{{ item }}"
    DOMAIN: "{{ item }}"
    TYPE: "{{ CONFIG[item].type }}"
    CFG: "{{ CONFIG[item].cfg }}"
    SIZE: "{{ CONFIG[item].size }}"
    ISO: "{{ CONFIG[item].iso }}"
    IMG: "{{ KVM_DIR }}/{{ NAME }}.img"
    OS: "{{ CONFIG[item].os }}"

    ISO_DIR: /mnt/depot/iso
    KVM_DIR: /mnt/vm2/kvm-pool
    VMW_DIR: /depot
    KS_ISO: "{{ NAME }}-oemdrv.iso"

    username: administrator@vsphere.local
    password: Passw0rd!
    vcenter: 192.168.1.97
    esxhost: 192.168.1.98
    datacenter: LAB
    datastore: DS01
    folder: template
    validate_certs: false

  tasks:

  - name: Building KVM images.
    include_tasks: "_LIB_/kvm-factory.yml"
    with_items: "{{ IMAGE }}"
    when: PROVISION=="KVM"

  - name: Building VMware images.
    include_tasks: "_LIB_/vmw-factory.yml"
    with_items: "{{ IMAGE }}"
    when: PROVISION=="VMW"
